### ISSUE TITLE
People can rejoin after their playing time (not as spectators)

### ISSUE THREAD

**Issue by wheatley2056** [CuukyOfficial/VaroPlugin#92] opened 2024-01-21 12:30 UTC
We are currently running a project with the plugin and have the bug that people can still return to the server after their playing time even though they are set to have only one session per day.

joinsystems.yml
```
catchUpSessions: false
ignoreJoinSystemsAsOP: true
joinAfterHours: -1
kickAtServerClose: false
massRecordingTime: 15
onlyJoinBetweenHours: true
onlyJoinBetweenHoursHour1: 15
onlyJoinBetweenHoursMinute1: 0
onlyJoinBetweenHoursHour2: 23
onlyJoinBetweenHoursMinute2: 0
preProduceSessions: 0
sessionsPerDay: 1
```

main.yml
```
dailyBackups: true
nametags:
  enabled: true
  visible:
    default: true
    team: true
    spectator: true
playTime: 20
prefix: '&7[&3LATEST&7]'
projectname: LATEST
projectnameColorcode: '&3'
language:
  main: de_de
  allowOther: true
crackedServer: false
resetSessionHour: 15
scoreboard: true
actionbar: true
supportPluginAds: false
unregisteredPlayerJoin: true
unregisteredPlayerJoinDuringGame: false
```

**Comment by Almighty-Satan** [comment] 2024-01-21 14:26
Could you please provide logs from the time when the problem first occurred?

**Comment by Almighty-Satan** [comment] 2024-02-02 10:28
I am closing this issue as I am unable to reproduce this and without logs it is impossible for me to say what might have caused this.

**Closed by Almighty-Satan** 2024-02-02 10:28 UTC
